### PR TITLE
AMQP fixes

### LINKED ISSUE #205: AMQP broker test is broken due to API change in lapin
See https://github.com/CleverCloud/lapin/issues/313. Once there is a work-around, ddebcb3258f53e584b981edc3824062f9d6d6e12 should be reverted.

### PR DESCRIPTION
**Pull request by Keruspe**
Fixes #205

### CODE REVIEW

**Comment by Keruspe** [comment]
Does this warrant a changelog entry?

File: src/broker/amqp.rs [hunk 1]
```diff
@@ -213,11 +213,9 @@ impl Broker for AMQPBroker {
     }
 
     async fn ack(&self, delivery: &Self::Delivery) -> Result<(), BrokerError> {
-        let _lock = self.consume_channel_write_lock.lock().await;
```
Comment (epwalsh) [inline src/broker/amqp.rs:216]: Did you mean to take this out? If so, are you sure it's okay to not acquire this lock here?

https://github.com/rusty-celery/rusty-celery/blob/ddebcb3258f53e584b981edc3824062f9d6d6e12/src/broker/amqp.rs#L134-L140

**Review by epwalsh — COMMENTED** [review]
Thanks @Keruspe! I don't think this warrants a CHANGELOG entry.

I just have one question about the change to the `ack` method.

File: src/broker/amqp.rs (hunk 1 above)
Comment (Keruspe) [reply src/broker/amqp.rs:216]: I'm not sure what the lock was for in the first place?

- the acker guarantees that you use the same channel for acking
- you can ack at any time, even if the channel is used by another thread, whether to read or write data, lapin ensures the correct ordrering of frames

Comment (epwalsh) [reply src/broker/amqp.rs:216]: Your 2nd bullet was what my question was really about.

> lapin ensures the correct ordering of frames

Is that a somewhat recent change? I originally added the lock because the worker was crashing when running on multiple threads under load. The error I was getting suggested it was due to incorrect frame ordering.

Comment (Keruspe) [reply src/broker/amqp.rs:216]: There used to be a problem wrt basic_publish frame ordering when other frames were in flight because the behaviour was poorly documented. We now properly consider all the frames from a basic publish to be contiguous as expected by rabbitmq.
The fix is fairly recent indeed (september) as it took some time to track down (actually had to read rabbitmq server code)

Comment (Keruspe) [reply src/broker/amqp.rs:216]: 1.2.6 and 1.2.7 were the relevant bugfix releases

Comment (epwalsh) [reply src/broker/amqp.rs:216]: Ahh gotcha! So in that case I think we can remove the `consume_channel_write_lock`:

https://github.com/rusty-celery/rusty-celery/blob/ddebcb3258f53e584b981edc3824062f9d6d6e12/src/broker/amqp.rs#L141

And we can probably use a `RwLock` instead of a `Mutex` around the `produce_channel`, right?

https://github.com/rusty-celery/rusty-celery/blob/ddebcb3258f53e584b981edc3824062f9d6d6e12/src/broker/amqp.rs#L132

I could make these changes in a separate PR unless you want to tack that onto this PR.

> actually had to read rabbitmq server code

That sounds like fun 😝

**Review by epwalsh — APPROVED** [review]
Looks great! Thanks @Keruspe!
